const fs = require('fs');
const path = '/Users/ice/Final-Project/lib/translations.ts';
let content = fs.readFileSync(path, 'utf8');

// The duplicate block at 193-232
const dupTH = `    book: {
      title: 'จองนัดหมาย',
      sub: 'กรอกรายละเอียดเพื่อนรักของคุณ ทีมงานจะยืนยันภายใน 24 ชั่วโมง',
      step1: 'กรอกข้อมูล',
      step2: 'ตรวจสอบ',
      step3: 'เสร็จสิ้น',
      serviceTitle: 'บริการที่ต้องการ',
      serviceLabel: 'ประเภทบริการ *',
      serviceSelect: 'กรุณาเลือกบริการ',
      otherLabel: 'โปรดระบุ *',
      otherPlaceholder: 'ระบุบริการ...',
      dateTitle: 'วันที่นัดหมาย',
      dateLabel: 'วันที่ *',
      timeLabel: 'เวลา *',
      ownerTitle: 'ข้อมูลเจ้าของ',
      ownerLabel: 'ชื่อเจ้าของ *',
      ownerPlaceholder: 'ชื่อ-นามสกุล',
      phoneLabel: 'เบอร์โทรศัพท์ *',
      phonePlaceholder: '08X-XXX-XXXX',
      petTitle: 'ข้อมูลสัตว์เลี้ยง',
      petNameLabel: 'ชื่อสัตว์เลี้ยง *',
      petNamePlaceholder: 'ชื่อน้องหมา/แมว',
      petTypeLabel: 'ประเภทสัตว์เลี้ยง *',
      otherPetPlaceholder: 'ระบุประเภทสัตว์เลี้ยง...',
      notesLabel: 'รายละเอียดเพิ่มเติม',
      notesPlaceholder: 'อาการ, ประวัติการรักษา, หรือข้อมูลอื่นๆ...',
      nextStep: 'ถัดไป → ตรวจสอบข้อมูล',
      summaryTitle: 'ตรวจสอบรายละเอียด',
      summarySub: 'กรุณาตรวจสอบข้อมูลก่อนยืนยันการจอง',
      confirmBooking: 'ยืนยันการจอง',
      bookingSuccess: 'จองนัดหมายสำเร็จ!',
      bookingSuccessSub: 'ทีมงานจะติดต่อกลับเพื่อยืนยันรายละเอียดภายใน 24 ชั่วโมง',
      emailSent: 'ระบบส่ง email ยืนยันแล้ว',
      bookNew: 'จองนัดใหม่',
      petDog: 'สุนัข',
      petCat: 'แมว',
      petRabbit: 'กระต่าย',
      petBird: 'นก',
      petOther: 'อื่นๆ',
    },
`;

const dupEN = `    book: {
      title: 'Book Appointment',
      sub: 'Fill in your pet\\'s details. Our team will confirm within 24 hours.',
      step1: 'Details',
      step2: 'Review',
      step3: 'Done',
      serviceTitle: 'Service Needed',
      serviceLabel: 'Service Type *',
      serviceSelect: 'Please select a service',
      otherLabel: 'Please specify *',
      otherPlaceholder: 'Specify service...',
      dateTitle: 'Appointment Date',
      dateLabel: 'Date *',
      timeLabel: 'Time *',
      ownerTitle: 'Owner Information',
      ownerLabel: 'Owner Name *',
      ownerPlaceholder: 'Full Name',
      phoneLabel: 'Phone Number *',
      phonePlaceholder: '08X-XXX-XXXX',
      petTitle: 'Pet Information',
      petNameLabel: 'Pet Name *',
      petNamePlaceholder: 'Dog/Cat Name',
      petTypeLabel: 'Pet Type *',
      otherPetPlaceholder: 'Specify pet type...',
      notesLabel: 'Additional Notes',
      notesPlaceholder: 'Symptoms, medical history, or other details...',
      nextStep: 'Next → Review Info',
      summaryTitle: 'Review Details',
      summarySub: 'Please review the information before confirming the booking',
      confirmBooking: 'Confirm Booking',
      bookingSuccess: 'Appointment Booked Successfully!',
      bookingSuccessSub: 'Our team will contact you to confirm the details within 24 hours',
      emailSent: 'Confirmation email sent',
      bookNew: 'Book Another Appointment',
      petDog: 'Dog',
      petCat: 'Cat',
      petRabbit: 'Rabbit',
      petBird: 'Bird',
      petOther: 'Other',
    },
`;

content = content.replace(dupTH, "");
content = content.replace(dupEN, "");

fs.writeFileSync(path, content);
console.log("Removed duplicate book blocks!");
